[project]
name = "simtastic-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram==3.21.0",
    "dotenv==0.9.9",
    "loguru==0.7.3",
    "python-dotenv==1.1.1",
]
